[project]
name = "agno-mcp"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=1.3.2",
    "duckduckgo-search>=8.0.1",
    "fastapi>=0.115.12",
    "groq>=0.22.0",
    "mcp>=1.6.0",
    "nest-asyncio>=1.6.0",
    "sqlalchemy>=2.0.40",
]
